server:
  port: 10000
spring:
  data: 
    mongodb: 
      name: user_details
      host: localhost
      port: 27017
      password: passw0rd
      username: u$er
migration.initial.file: /migration/initial/user_preferences.json